config/routes.rb
StadiumGuide::Application.routes.draw do
  resources :cities, :stadia

  

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :city
	belongs_to :league
end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :stadium, dependent: :destroy
	has_many :assignment
	has_many :league, through: :assignment
end

app/models/league.rb
class League < ActiveRecord::Base
	has_many :assignment
	has_many :city, through: :assignment
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/stadium.rb
class Stadium < ActiveRecord::Base
	belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.includes(:stadium).all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render action: 'show', status: :created, location: @city }
      else
        format.html { render action: 'new' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state, :sportsness)
    end
end

app/controllers/stadia_controller.rb
class StadiaController < ApplicationController
  before_action :set_stadium, only: [:show, :edit, :update, :destroy]

  # GET /stadia
  # GET /stadia.json
  def index
    @stadia = Stadium.all
  end

  # GET /stadia/1
  # GET /stadia/1.json
  def show
  end

  # GET /stadia/new
  def new
    @stadium = Stadium.new
  end

  # GET /stadia/1/edit
  def edit
  end

  # POST /stadia
  # POST /stadia.json
  def create
    @stadium = Stadium.new(stadium_params)

    respond_to do |format|
      if @stadium.save
        format.html { redirect_to @stadium, notice: 'Stadium was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stadium }
      else
        format.html { render action: 'new' }
        format.json { render json: @stadium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stadia/1
  # PATCH/PUT /stadia/1.json
  def update
    respond_to do |format|
      if @stadium.update(stadium_params)
        format.html { redirect_to @stadium, notice: 'Stadium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stadium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stadia/1
  # DELETE /stadia/1.json
  def destroy
    @stadium.destroy
    respond_to do |format|
      format.html { redirect_to stadia_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stadium
      @stadium = Stadium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stadium_params
      params.require(:stadium).permit(:name, :city_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/stadia_helper.rb
module StadiaHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </div>
  <div class="field">
    <%= f.label :sportsness %><br>
    <%= f.number_field :sportsness %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>Sportsness</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.state %></td>
        <td><%= city.sportsness %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @city.state %>
</p>

<p>
  <strong>Sportsness:</strong>
  <%= @city.sportsness %>
</p>

<table>
  <thead>
    <tr>
      <th>Venues:</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  	<% stadiums = Stadium.where(city_id: @city.id) %>
    <% stadiums.each do |s| %>
      <tr>
        <td><%= link_to "#{s.name}", s %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    <em><%= 'No stadiums in this city' if stadiums.empty? %></em>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StadiumGuide</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stadia/_form.html.erb
<%= form_for(@stadium) do |f| %>
  <% if @stadium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stadium.errors.count, "error") %> prohibited this stadium from being saved:</h2>

      <ul>
      <% @stadium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.number_field :city_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stadia/edit.html.erb
<h1>Editing stadium</h1>

<%= render 'form' %>

<%= link_to 'Show', @stadium %> |
<%= link_to 'Back', stadia_path %>

app/views/stadia/index.html.erb
<h1>Listing stadia</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stadia.each do |stadium| %>
      <tr>
        <td><%= stadium.name %></td>
        <td><%= City.find(stadium.city_id).name %></td>
        <td><%= link_to 'Show', stadium %></td>
        <td><%= link_to 'Edit', edit_stadium_path(stadium) %></td>
        <td><%= link_to 'Destroy', stadium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stadium', new_stadium_path %>

app/views/stadia/new.html.erb
<h1>New stadium</h1>

<%= render 'form' %>

<%= link_to 'Back', stadia_path %>

app/views/stadia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stadium.name %>
</p>

<p>
  <strong>City:</strong>
  <%= City.find(@stadium.city_id).name %>
</p>

<%= link_to 'Edit', edit_stadium_path(@stadium) %> |
<%= link_to 'Back', stadia_path %>